version: "3.8"

services:
  duck_bot:
    build:
      context: .
    # container_name: Duck_bot
    restart: always
    environment:
      - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
      - GROUP_CHAT_ID=${GROUP_CHAT_ID}
      - MORNING_STICKER_ID=${MORNING_STICKER_ID}
      - EVENING_STICKER_ID=${EVENING_STICKER_ID}
    volumes:
      # - .:/app
      - ./logs:/app/logs
